//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPhimV1.Admin.NguoiDungs {
    
    
    public partial class NapCoin {
        
        /// <summary>
        /// UiNapCoin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPhimV1.Control_Admin.NguoiDungs.UiNapCoin UiNapCoin;
    }
}
